kind = "web"
previewPath = "/"
title = "Editor de Texto"
version = "1.0.0"
id = "artifacts/editor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25484

[services.development]
run = "pnpm --filter @workspace/editor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/editor", "run", "build" ]
publicDir = "artifacts/editor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25484"
BASE_PATH = "/"
